location = {
    0 : {"Start" : 4000},
    1 : {"Brun" : "Västerlånggatan"},
    2 : {"Allmänning" : "Allmänning"},
    3 : {"Brun" : "Hornsgatan"},
    4 : {"Skatt" : 4000},
    5 : {"Station" : "Södra Station"},
    6 : {"Ljus-Blå" : "Folkungagatan"},
    7 : {"Chans" : "Chans"},
    8 : {"Ljus-Blå" : "Götgatan"},
    9 : {"Ljus-Blå" : "Ringvägen"},
    10 : {"Fängelse" : "Besök"},
    11 : {"Rosa" : "S:T Eriksgatan"},
    12 : {"Statligt" : "Elverket"},
    13 : {"Rosa" : "Odengatan"},
    14 : {"Rosa" : "Valhallavägen"},
    15 : {"Station" : "Östra Station"},
    16 : {"Orange" : "Sturegatan"},
    17 : {"Allmänning" : "Allmänning"},
    18 : {"Orange" : "Karlavägen"},
    19 : {"Orange" : "Narvavägen"},
    20 : {"Fri Parkering" : "Fri Parkering"},
    21 : {"Röd" : "Strandvägen"},
    22 : {"Chans" : "Chans"},
    23 : {"Röd" : "Kungsträdgårdsgatan"},
    24 : {"Röd" : "Hamngatan"},
    25 : {"Station" : "Central Station"},
    26 : {"Gul" : "Vasagatan"},
    27 : {"Gul" : "Kungsgatan"},
    28 : {"Statligt" : "Vattenledningsverket"},
    29 : {"Gul" : "Stureplan"},
    30 : {"Fängelse" : "Fängelse"},
    31 : {"Grön" : "Gustav Adolfs Torg"},
    32 : {"Grön" : "Drottninggatan"},
    33 : {"Allmänning" : "Allmänning"},
    34 : {"Grön" : "Diplomatstaden"},
    35 : {"Station" : "Norra Station"},
    36 : {"Chans" : "Chans"},
    37 : {"Blå" : "Centrum"},
    38 : {"Skatt" : 2000},
    39 : {"Blå" : "Norrmalmstorg"}
}